[build]
  base    = "frontend"
  command = "flutter build web --release"
  publish = "build/web"

[[plugins]]
  package = "@nicholasmireles/flutter-build-static-assets"
  version = "latest"

[environment]
  API_BASE_URL = "https://trichat.onrender.com"
