// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sG4d_9JRiZjbDcfRP-7YVAbFdMkZRX0',
    appId: '1:1004023558166:android:6100bcc9041b00ef094537',
    messagingSenderId: '1004023558166',
    projectId: 'zalo-lite-v2',
    storageBucket: 'zalo-lite-v2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMEptedzwcIzIzH0gCxF29WpUTtthnEU',
    appId: '1:1004023558166:ios:749e2d878480914f094537',
    messagingSenderId: '1004023558166',
    projectId: 'zalo-lite-v2',
    storageBucket: 'zalo-lite-v2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaxGgjUGYHJfLEHZ9OdvC29T-NlXGyjyo',
    appId: '1:1004023558166:web:e44c5cbc606d7d59094537',
    messagingSenderId: '1004023558166',
    projectId: 'zalo-lite-v2',
    authDomain: 'zalo-lite-v2.firebaseapp.com',
    storageBucket: 'zalo-lite-v2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMEptedzwcIzIzH0gCxF29WpUTtthnEU',
    appId: '1:1004023558166:ios:749e2d878480914f094537',
    messagingSenderId: '1004023558166',
    projectId: 'zalo-lite-v2',
    storageBucket: 'zalo-lite-v2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaxGgjUGYHJfLEHZ9OdvC29T-NlXGyjyo',
    appId: '1:1004023558166:web:f90a6f7dba144809094537',
    messagingSenderId: '1004023558166',
    projectId: 'zalo-lite-v2',
    authDomain: 'zalo-lite-v2.firebaseapp.com',
    storageBucket: 'zalo-lite-v2.firebasestorage.app',
  );
}