// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9cXmozuEik7XuChb28RkD-qgeUonHK4M',
    appId: '1:704895954808:android:b02245d793cc371a33228d',
    messagingSenderId: '704895954808',
    projectId: 'zalo-lite-f2d28',
    storageBucket: 'zalo-lite-f2d28.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUaWo01Sbz4tWevWseHLbbaHkB9mAd2s',
    appId: '1:704895954808:ios:placeholder',
    messagingSenderId: '704895954808',
    projectId: 'zalo-lite-f2d28',
    storageBucket: 'zalo-lite-f2d28.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUaWo01Sbz4tWevWseHLbbaHkB9mAd2s',
    appId: '1:704895954808:web:e3e92bc82bdfac0933228d',
    messagingSenderId: '704895954808',
    projectId: 'zalo-lite-f2d28',
    authDomain: 'zalo-lite-f2d28.firebaseapp.com',
    storageBucket: 'zalo-lite-f2d28.firebasestorage.app',
    measurementId: 'G-E5XRXFLN9B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKUaWo01Sbz4tWevWseHLbbaHkB9mAd2s',
    appId: '1:704895954808:ios:placeholder',
    messagingSenderId: '704895954808',
    projectId: 'zalo-lite-f2d28',
    storageBucket: 'zalo-lite-f2d28.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKUaWo01Sbz4tWevWseHLbbaHkB9mAd2s',
    appId: '1:704895954808:web:7d48d5c618e49a3933228d',
    messagingSenderId: '704895954808',
    projectId: 'zalo-lite-f2d28',
    authDomain: 'zalo-lite-f2d28.firebaseapp.com',
    storageBucket: 'zalo-lite-f2d28.firebasestorage.app',
    measurementId: 'G-LFNPD9FV3S',
  );
}